### ISSUE TITLE
Typo errors

### ISSUE THREAD

**Issue by raphaelfabeni** [rafaell-lycan/rafaell-lycan.github.com#21]
In this [post](http://rafaell-lycan.com/2015/comecando-com-react/) I found some typo errors. I'll list here:

* O React renderiza novamente utilizando o **Virutal** DOM;
* Também vale **resaltar**;

**Comment by rafaell-lycan** [comment]
Thanks a lot @raphaelfabeni, I'll improve it today :+1:
